### ISSUE TITLE
stderr must not appear in the response

### ISSUE THREAD

**Issue by luxifer** [hoaproject/Fastcgi#18]
In a normal FactCGI request to a nonexistent scrip I got:

#### stderr:
```
Primary script unknown
```
#### stdout:
```
Status: 404 Not Found
X-Powered-By: PHP/7.1.10
Content-type: text/html; charset=UTF-8

File not found.
```

But in the raw response handled by this lib I got this in the same var.

```
Primary script unknown
Status: 404 Not Found
X-Powered-By: PHP/7.1.10
Content-type: text/html; charset=UTF-8

File not found.
```

I saw this in the Responder:

https://github.com/hoaproject/Fastcgi/blob/b741a49c0e0638ac7f43b6689fc25b563a5f6e46/Responder.php#L226-L229

But in my opinion stdout and stderr must not bu multiplexed

**Comment by luxifer** [comment]
Because of the multiplexing, the headers ar incorrectly parsed:

```php
array(3) {
  'primary script unknown
status' =>
  string(13) "404 Not Found"
  'x-powered-by' =>
  string(10) "PHP/7.1.10"
  'content-type' =>
  string(24) "text/html; charset=UTF-8"
}
```
instead of:
```php
array(3) {
  'status' =>
  string(13) "404 Not Found"
  'x-powered-by' =>
  string(10) "PHP/7.1.10"
  'content-type' =>
  string(24) "text/html; charset=UTF-8"
}
```

**Comment by Hywan** [comment]
The bug is valid. Let's see #19.
