### ISSUE TITLE
Resolve class names

### ISSUE THREAD

**Issue by k42b3** [hoaproject/Fastcgi#22]
Hi, this project looks really great. My problem is not an issue in the library itself but more a UX issue of the code. The problem is simply that PHPStorm can not resolve some class relations (i.e. the `Connection` class in `Hoa\Socket\Client`). I guess the reason is because there is a method `Consistency::flexEntity` which sets class aliases. So I simply want to let you know that this problem exists and whether its not simpler to use the actual class names in the code?

**Comment by Pierozi** [comment]
We provide stubs files for resolve the flex class resolution in IDE.
You can generate yourself usign command `expandflexentities` in https://github.com/hoaproject/Devtools

Details information in PR https://github.com/hoaproject/Devtools/pull/43

**Comment by k42b3** [comment]
Ok, thanks for the info. Just out of curiosity, what is the concrete reason to use `Consistency::flexEntity`, is it only to have a short class name? Also I will close this issue since there is nothing more todo here.

**Comment by Pierozi** [comment]
Yes mainly find more information on `Hoa\Consistency` repository

> Flexible entities
> 
> Flexible entities are very simple. If we declare Foo\Bar\Bar as a flexible entity, we will be able to access it with the Foo\Bar\Bar name or Foo\Bar. This is very useful if your architecture evolves but you want to keep the backward compatibility. For instance, it often happens that you create a Foo\Bar\Exception class in the Foo/Bar/Exception.php file. But after few versions, you realise other exceptions need to be introduced, so you need an Exception directory. In this case, Foo\Bar\Exception should move as Foo\Bar\Exception\Exception. If this latter is declared as a flexible entity, backward compatibility will be kept.
