### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by luxifer** [hoaproject/Fastcgi#23]
Hi,

I was thinking when will you have the time to make a new release for this project?

Regards.

**Comment by mnapoli** [comment]
Pinging again @Hywan, we need a new release in Bref (the fix is already on master).

**Comment by Hywan** [comment]
Hello :-),

A new released is scheduled for the end of March. How does it sound for you?

**Comment by mnapoli** [comment]
This is unfortunately a long time for us but it's open source, we'll take whatever you can do :)

**Comment by Hywan** [comment]
Mid-March :-)?

**Comment by mnapoli** [comment]
:+1: :) thanks

**Comment by Hywan** [comment]
I did a pre-release for you, https://github.com/hoaproject/Fastcgi/releases/tag/3.19.02.19. Hope it helps!

**Comment by mnapoli** [comment]
@Hywan awesome thank you!
