### ISSUE TITLE
HTTP response headers leak between requests

### ISSUE THREAD

**Issue by mnapoli** [hoaproject/Fastcgi#24]
HTTP response headers are stored in a class property as an array:

https://github.com/hoaproject/Fastcgi/blob/2bd7b2476220d30a69b366436d7d282d78b42b1e/Responder.php#L298

but they are never cleared! That means that if a request A sets a response header which doesn't exist in a subsequent request B, then B will have A's response header.

We stumbled on that in Bref, reported in https://github.com/mnapoli/bref/issues/249

**Comment by Hywan** [comment]
Thanks for the bug report. I will fix that!

**Comment by taylorotwell** [comment]
Header parsing is also broken for headers that may have multiple entries... for example, `Set-Cookie`... only the last `Set-Cookie` header will be preserved since Hoa builds a simple key / value array of header => values. Each header key should actually be an array of values.

**Comment by Hywan** [comment]
Multi-headers support is fixed in #28.

**Comment by Hywan** [comment]
@mnapoli They are cleared, here, https://github.com/hoaproject/Fastcgi/blob/master/Responder.php#L192. Am I missing something?

**Comment by mnapoli** [comment]
:+1: From the code it seems this issue was fixed after it was reported (in the 3.19.02.19 release).

**Comment by Hywan** [comment]
:+1:
